packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@nestjs/core': true
  '@prisma/engines': true
  '@scarf/scarf': true
  '@swc/core': true
  es5-ext: true
  esbuild: true
  node-sass: true
  prisma: true
  unrs-resolver: true
