FROM docker.io/library/node:24-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g pnpm@11.5.0

FROM base AS build
WORKDIR /usr/src/app

COPY pnpm-lock.yaml pnpm-workspace.yaml package.json ./
COPY packages/ ./packages/
COPY apps/frontend/ ./apps/frontend/

RUN --mount=type=cache,id=pnpm,target=/pnpm/store pnpm install --frozen-lockfile

ARG VITE_TITLE
ARG VITE_BACKEND_API_URL

ENV VITE_TITLE=$VITE_TITLE
ENV VITE_BACKEND_API_URL=$VITE_BACKEND_API_URL

RUN pnpm --filter shared build
RUN pnpm --filter ./apps/frontend build

FROM docker.io/library/nginx:alpine AS runner
COPY --from=build /usr/src/app/apps/frontend/dist /usr/share/nginx/html

RUN echo $'\
server {\n\
    listen 80;\n\
    location / {\n\
        root /usr/share/nginx/html;\n\
        index index.html index.htm;\n\
        try_files $uri $uri/ /index.html;\n\
    }\n\
}' > /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]